### ISSUE TITLE
cloudbuddy disabling mounting if `fuse` is not a module

### ISSUE THREAD

**Issue by theofficialgman** [Botspot/cloudbuddy#7] opened 2022-01-30 21:46 UTC
In my kernel, fuse is a builtin driver, not a module. The main.sh script disables features if `fuse` is not a module

The availability of fuse as a builtin or module driver can be checked with: 
```
ls /sys/module | grep -Fx fuse
```

and yes, I have checked the builtin version of fuse works fine with the script otherwise if you make the below edit

**Comment by theofficialgman** [comment] 2022-01-30 21:52
changing this:
https://github.com/Botspot/cloudbuddy/blob/4b9535cc3237525a4852ae000253e53b3160f2b8/main.sh#L170

to this:
```
if ! ls /sys/module | grep -Fxq fuse ;then
```
should work in both cases I think

**Comment by Botspot** [comment] 2022-01-31 04:42
Ultimately, the script has to determine if a fuse-mount will succeed.

Currently it does this by checking if the `fuse` module is loaded, which as you pointed out, doesn't work in your kernel. However, your solution is faulty because it would allow old kernels, that are missing the fuse module, to pass through the test.

Your suggested change is:
`if ! ls /sys/module | grep -Fxq fuse ;then`
This is basically checking if the fuse module is missing! If that's the entire check right there, then there's a possibility that the fuse module is built-in, or that it is completely unavailable.

**Comment by theofficialgman** [comment] 2022-01-31 04:55
> Your suggested change is: `if ! ls /sys/module | grep -Fxq fuse ;then` This is basically checking if the fuse module is missing! If that's the entire check right there, then there's a possibility that the fuse module is built-in, or that it is completely unavailable.

@Botspot 
no... I'm pretty sure my check is good. It will show that fuse is either builtin or already loaded as a module and skip your modprobe. If fuse is not present in the `/sys/module` (like if the module is unloaded or not in the kernel at all), then the contents of that `if` statement will run. Fuse shouldn't be present in /sys/module if its unloaded which is why my check works in both cases

NOTE, this is line 170 as indicated, not 176

**Comment by theofficialgman** [comment] 2022-01-31 04:57
just run `sudo modprobe -r fuse` to unload the module and then `ls /sys/module | grep -Fx fuse` and tell me if there is any fuse grepped. if there is no output, then all is good and you should include my change

**Comment by theofficialgman** [comment] 2022-02-15 04:25
@Botspot  can you read my previous messages again? I'm pretty sure I'm right here and with the latest changes to pi-apps loading kernel modules, I'm sure you could do something similar here

**Comment by Botspot** [comment] 2022-03-21 21:21
@theofficialgman, does the `enable_module` function in the Pi-Apps api work for you? That function is also grepping the output `lsmod`, so if you have problems here then you should have problems there.

**Comment by theofficialgman** [comment] 2022-03-21 21:26
> @theofficialgman, does the `enable_module` function in the Pi-Apps api work for you? That function is also grepping the output `lsmod`, so if you have problems here then you should have problems there.

running `enable_module`modprobes the module even if its builtin to the kernel. it doesn't fail/exit because modprobe doesn't output an error if the kernel module itself is present (aka, the exit code of the modprobe is still 0)
so I guess `enable_module` works fine enough, yeah

**Comment by theofficialgman** [comment] 2022-03-21 21:31
I still don't really understand why you don't use this:
```if ! ls /sys/module | awk '{print $1}' | grep -qFx "$module" ;then```
/sys/module contains all kernel builtin and module based drivers

and replace what you current use:
``` if ! lsmod | awk '{print $1}' | grep -qxF "$module" ;then```

**Comment by Botspot** [comment] 2022-03-21 21:33
Is /sys/module a static filesystem of physical module binaries, or is it a virtual kernel filesystem that lists *currently running modules*?

**Comment by theofficialgman** [comment] 2022-03-21 21:35
> Is /sys/module a static filesystem of physical module binaries, or is it a virtual kernel filesystem that lists _currently running modules_?

currently running modules, I just unloaded a module that was in the list to check that. it is gone from ls /sys/module and lsmod now

**Comment by theofficialgman** [comment] 2022-03-21 21:38
so basically /sys/module is a list of builtin kernel modules + loaded not-builtin modules, while lsmod gives a list of just the loaded not-builtin modules

**Comment by Botspot** [comment] 2022-03-21 21:50
> so basically /sys/module is a list of builtin kernel modules + loaded not-builtin modules, while lsmod gives a list of just the loaded not-builtin modules

Thank you. I must have been mixing it up with /lib/modules.

**Comment by Botspot** [comment] 2022-03-21 21:54
Okay, it should be fixed now.

**Closed as completed** 2022-03-21 21:54 UTC

**Comment by michTmon** [comment] 2026-03-20 02:39
For some reason, this fix isn't working on my CloudBuddy installed from Pi-Apps. I checked line 170 and it looks right as to above.

rclone v1.73.2
- os/version: raspbian 12.12
- os/kernel: 5.17.0-rc4-next-20220217-g21d89a4d51a7 (armv7l)
- os/type: linux
- os/arch: arm (ARMv7 compatible)
- go/version: go1.25.8
- go/linking: static
- go/tags: none
usr@raspberrypi:~ $ rclone selfupdate
2026/03/20 02:37:48 NOTICE: rclone is up to date

**Comment by Botspot** [comment] 2026-03-20 04:19
> For some reason, this fix isn't working on my CloudBuddy installed from Pi-Apps. I checked line 170 and it looks right as to above.
> 
> rclone v1.73.2
> 
> * os/version: raspbian 12.12
> * os/kernel: 5.17.0-rc4-next-20220217-g21d89a4d51a7 (armv7l)
> * os/type: linux
> * os/arch: arm (ARMv7 compatible)
> * go/version: go1.25.8
> * go/linking: static
> * go/tags: none
>   usr@raspberrypi:~ $ rclone selfupdate
>   2026/03/20 02:37:48 NOTICE: rclone is up to date

@michTmon please run these commands and send back the output:
```
modinfo --filename fuse
ls /sys/module | awk '{print $1}' | grep -qFx fuse
file /lib/modules/$(uname -r)
file /sys/module/fuse
```

**Comment by michTmon** [comment] 2026-03-20 06:07
usr@raspberrypi:~ $ modinfo --filename fuse
modinfo: ERROR: Module fuse not found.
usr@raspberrypi:~ $ ls /sys/module | awk '{print $1}' | grep -qFx fuse
usr@raspberrypi:~ $ file /lib/modules/$(uname -r)
/lib/modules/5.17.0-rc4-next-20220217-g21d89a4d51a7: directory
usr@raspberrypi:~ $ file /sys/module/fuse
/sys/module/fuse: cannot open `/sys/module/fuse' (No such file or directory)
usr@raspberrypi:~ $

**Comment by Botspot** [comment] 2026-03-20 06:11
> usr@raspberrypi:~ $ modinfo --filename fuse modinfo: ERROR: Module fuse not found. usr@raspberrypi:~ $ ls /sys/module | awk '{print $1}' | grep -qFx fuse usr@raspberrypi:~ $ file /lib/modules/$(uname -r) /lib/modules/5.17.0-rc4-next-20220217-g21d89a4d51a7: directory usr@raspberrypi:~ $ file /sys/module/fuse /sys/module/fuse: cannot open `/sys/module/fuse' (No such file or directory) usr@raspberrypi:~ $

Looks like your kernel is truly missing the fuse module, and cloudbuddy is working as intended.

**Comment by michTmon** [comment] 2026-03-20 06:34
Thanks for your help. I truly have no idea what I'm doing. My previous attempt to install fuse didn't work because installing fuse seems to be bad:

```
usr@raspberrypi:~ $ sudo apt install fuse
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libfuse3-3 libinih1 libntfs-3g89
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  fuse3 gvfs-fuse ntfs-3g xdg-desktop-portal xdg-desktop-portal-gtk
  xdg-desktop-portal-wlr
The following NEW packages will be installed:
  fuse
0 upgraded, 1 newly installed, 6 to remove and 126 not upgraded.
Need to get 58.0 kB of archives.
After this operation, 3,741 kB disk space will be freed.
Do you want to continue? [Y/n] n
Abort.
```

The internet said to instead use libfuse2 but neither that nor fuse3 seem to satisfy cloudbuddy.

```
libfuse2 is already the newest version (2.9.9-6).
fuse3 is already the newest version (3.14.0-4).
gvfs-fuse is already the newest version (1.50.3-1).
E: Unable to locate package fuse-utils
```

If the move here is to just install fuse and later recover all the broken stuff from bash, I guess I'll do it. Mounting a cloud drive is critical for my use case.

Or [I get crazier...?](https://www.agwa.name/blog/post/easily_running_fuse_in_an_isolated_mount_namespace)

**Comment by Botspot** [comment] 2026-03-20 13:49
@michTmon The fuse packages on apt won't help you here. The kernel itself needs a fuse module. Think of it as a hardware driver. You probably need to recompile your kernel and ensure the fuse module is enabled. Or if you're using a namespace, let it pass through somehow.
